### PR TITLE
Fixed issue with InputTextMultiline/Password Flag issue #3427

### PR DESCRIPTION
**Pull request by hoffstadt**
Simple fix for an issue when using InputTextMultiline with the "ImGuiInputTextFlags_Password".

### CODE REVIEW

**Comment by ocornut** [comment]
I believe this will fail/assert on non-password multiline fields.

**Comment by hoffstadt** [comment]
Wow. Sorry about that. Dumb mistake. I updated it!

**Comment by hoffstadt** [comment]
This should be good to go now. Please let know know if I missed anything else trivial. Ha

**Comment by ocornut** [comment]
Hello, thanks for reporting this. I didn't pick your commit as-is because it was unnecessarily complex and didn't follow the coding style, but applied an equivalent fix in 32be6c064b9036341fd36e7c34a11f2dc4104f6c. Thanks again!

**Pull request closed without merging**
