### PR TITLE
Remove SDL2 method from SDL3 backend

### PR DESCRIPTION
**Pull request by Narmjep**
Kindly look at the commit's comments for more information

### CODE REVIEW

**Comment by myo** [comment]
+1, imgui won't compile without doing this.

**Comment by sakiodre** [comment]
I suggest removing it completely instead of commenting it

**Comment by Narmjep** [comment]
My bad. I removed it now

**Comment by ocornut** [comment]
Thanks for this!
I have pushed the proper fix 162f8e0 for this.
You may have noticed the corresponding header file had a `ImGui_ImplSDL3_InitForOther()` function declared which was added in 1e17d59 where I made the typo (\*). 

When making changes it's generally a good idea to use git log and git blame to learn more about the context.

(We have no CI for SDL3 as it's still rather unstable API and unpackaged.)

**Pull request closed without merging**
