### PR TITLE
Slidershrink

### PR DESCRIPTION
**Pull request by ebachard**
First PR try with this feature.

slider thickness : allows to modify the slider thickness, as shown in https://github.com/ocornut/imgui/issues/2263 , **following @ocornut  recommendations**: 
- value 0.0f means rectangle is not shrinked ;
- value 1.0f means rectangle is completely shrinked ;
- when 0.0f value is used (basic slider rectangle), do not calculate shrink _amount, to save cycles.

Works well with SDL2 + OpenGL3 (not tested other renderers)
I don't see any warning, but I only tested on Linux with g++  ( 5.4.0 and 5.7.1)

Thanks in advance for your feedback, and for every change you suggest.

I simply hope this feature will help (I'm using it since a while without any issue since a while).

### CODE REVIEW

**Comment by ocornut** [comment]
Hello and thanks.
Quick feedback:

- Remove the unrelated changes.
- Squash the commits.
- You are using 1.0f - Scale multplier which makes it not a Scale. We use “Scale” value everywhere, 1.0f should be “no change”.

**Comment by ebachard** [comment]
Ouch, what's this mess ? 

@ocornut , apologies, looks like the PR contains a lot of unwanted things  :-/

Honestly, I don't understand what happens :  I created a separated branch, named sliderthickness, and I wonder why every changes I did are included in this PR ... ?

**Comment by frink** [comment]
It seems this is an abandoned PR. I'm thinking of taking up the changes and preparing it for inclusion. If I understand correctly, you want the scale to be reversed and the commit squashed without the style... Is that correct @ocornut?

**Comment by ocornut** [comment]
Closing moving this to #3599

**Pull request closed without merging**
