### PR TITLE
TreeNodeEx: Bullet and Leaf flags now work on Framed node (#2159)

### PR DESCRIPTION
**Pull request by goran-w**
The Bullet and Leaf ImGuiTreeNodeFlags are now taken into account for Framed/CollapsingHeader tree nodes as well. TreeNodeEx() can be used to specify these flags. A choice was made to left-adjust the Framed text when no Bullet/Arrow is rendered, since this was deemed to look better in the Framed context (especially when considering that CollapsingHeader is drawn using NoTreePushOnOpen, so child/sibling Text items etc will often be non-indented).

### CODE REVIEW

**Comment by ocornut** [comment]
Hello @goran-w , sorry for the late answer. I can merge this feature now, but I am curious how you are using both flags in the context of a CollapsingHeader() - in particular using the bullet flag here seems a little surprising.

**Comment by goran-w** [comment]
I think it’s mostly about consistency and having these flags have the expected effect, being able to match the effects on tree nodes for CollapsingHeader as well.

I described the usage with screenshots in the associated issue: https://github.com/ocornut/imgui/issues/2159

**Comment by goran-w** [comment]
How I've actually used it so far is to define my own NonCollapsingHeader with flags:
_Framed | _NoTreePushOnOpen | _Leaf

**Comment by ocornut** [comment]
Apologies I had forgotten the other thread. All sounds good, will merge soon!

**Comment by goran-w** [comment]
NOTE: there were merge conflicts that I resolved on my branch today, but I have no time to test this today. Could you review my small change?
I made text_pos non-const in order to left-adjust text without Bullet/Arrow. The default (!is_leaf) branch is the same as before, so only the Bullet and/or Leaf branches are untested after conflict resolve. The bullet rendering line is copied from the un-framed case...

**Comment by ocornut** [comment]
Merged now. I made minor tweak (offset the bullet to the left). Thanks!

**Pull request closed without merging**
