### PR TITLE
Examples: Fixed Vulkan window resizing crash.

### PR DESCRIPTION
**Pull request by TheLavaBlock**
Handles `VK_ERROR_OUT_OF_DATE_KHR` when resizing the window. 

For more info: ["Suboptimal or out-of-date swap chain" in Vulkan Tutorial](https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation#page_Suboptimal_or_out_of_date_swap_chain)

Got this error on latest Ubuntu 16.04 LTS. 

**Interesting:** 
When enabling `VK_LAYER_LUNARG_standard_validation` with `IMGUI_VULKAN_DEBUG_REPORT` we get another crash. 

But this might be another problem, see chromium bug report: [vulkan: Don't enable VK_LAYER_LUNARG_standard_validation under X11 ](https://github.com/chromium/chromium/commit/8fcdbf04ac7ff9fe0d0d3dcf125e41810959964c)

### CODE REVIEW

**Comment by ocornut** [comment]
Thank you @TheLavaBlock. 

I would like to ask you for a favor, could you check and possibly look into making the equivalent fix for the code in the Viewport branch? https://github.com/ocornut/imgui/tree/viewport/examples
Perhaps the bug doesn't apply anymore in the Viewport branch.

The examples and in particular the Vulkan code have been severely refactored (they are still issue with present when using multi-viewports, but this shouldn't affect this change you are proposing).

**Comment by TheLavaBlock** [comment]
Sure @ocornut - I will take a look at the [Viewport](https://github.com/ocornut/imgui/tree/viewport) branch and update / close this PR. 

Good point.

**Comment by ocornut** [comment]
No need to close this one, depending on the timeline of moving the refactored example to master I may merge this earlier in master.

**Comment by ocornut** [comment]
@TheLavaBlock I merged the refactored examples in master, so your PR unfortunately need to be rework, sorry for that. I can't seem to repro the issue under Windows (I tried with latest VulkanSDK 1.1.73 + validation layer) so I'd rather not attempt to blind fix it.

**Comment by TheLavaBlock** [comment]
@ocornut Alright - have to check it. Will open new PR if necessary. Thanks for your feedback.

**Pull request closed without merging**
