### PR TITLE
Imstr

### PR DESCRIPTION
**Pull request by bitshifter**
Tracking PR for issue #494.

### CODE REVIEW

**Comment by krux02** [comment]
As much as I like the idea, it has has the problem that it breaks all wrapper code for imgui, and I am considering to write a wrapper right now at this moment.

**Comment by paulsapps** [comment]
You'd just need to update the binding to also pass the string length instead of just a pointer to a string

**Comment by bitshifter** [comment]
@krux02  The main motivation for this change was for calling dear imgui from Rust (as Rust strings are not null-terminated). As part of this work I have also branched cimgui (a C imgui wrapper) to support these changes at https://github.com/bitshifter/cimgui/tree/imstr.

**Comment by krux02** [comment]
An idea to not create breaking changes is to make `ImStr` just an alias of `const char*` by default. Only when use the `ImStr` struct when preprocessor flag is set.

```C++
#ifdef USE_IM_STR_STRUCT
struct ImStr
[...]
#else
using ImStr = const char*;
#endif
```

**Comment by ocornut** [comment]
FYI @rokups has revived this PR as #3038.

**Comment by ocornut** [comment]
Closing as moved to #3038

**Pull request closed without merging**
