### PR TITLE
Negative-sized clip rects are forbidden in GL

### PR DESCRIPTION
**Pull request by adamdmoss**
At first I assert()d ImDrawList::AddDrawCmd() to detect these at their source, but it seems that ImGui generates these pretty often, so I just made the GL example implementations clamp their sizes down to 0 in these cases.

### CODE REVIEW

**Comment by ocornut** [comment]
ImGui shouldn't generate them!
I think it may due to that change I just did with the title bar
Line 3320
Can you try replacing
```
    window->SkipItems = (window->Collapsed || !window->Visible) && window->AutoFitFrames == 0;
```
With
```
    window->SkipItems = (window->Collapsed) || (!window->Visible && window->AutoFitFrames == 0);
```
?

**Comment by ocornut** [comment]
Could you post a repro of when ImGui is creating negative clip rectangle?

**Comment by adamdmoss** [comment]
That doesn't seem to help.
The culprit (well, the first one that causes an assert anyway) seems to be the cliprect pushed at imgui.cpp:3295

```c++
    // Inner clipping rectangle
    // We set this up after processing the resize grip so that our clip rectangle doesn't lag by a frame
    const ImRect title_bar_rect = window->TitleBarRect();
    ImVec4 clip_rect(title_bar_rect.Min.x+0.5f+window->WindowPadding().x*0.5f, title_bar_rect.Max.y+0.5f, window->Rect().Max.x+0.5f-window->WindowPadding().x*0.5f, window->Rect().Max.y-1.5f);
    if (window->ScrollbarY)
        clip_rect.z -= style.ScrollbarWidth;
    PushClipRect(clip_rect);
```

ShowTestWindow() is enough to make this happen.

**Comment by ocornut** [comment]
Have you changed any imgui settings?
Just calling ShowTestWindow() triggers the assert that you added in the rendering?

**Comment by adamdmoss** [comment]
Apply this patch to hopefully see for yourself:
https://github.com/adamdmoss/imgui/commit/276a3e24f649b7bd76ca729dad6bb1fc8b3c4be4.diff

**Comment by adamdmoss** [comment]
I'm using a custom font, that's the only global change I've made.  Otherwise I'm using your imgui master without any local changes.

**Comment by adamdmoss** [comment]
opengl3_example's imgui_example shows this problem if you try to collapse the ImGui Test window at least.
The offender is imgui.cpp:3295 again.

**Comment by ocornut** [comment]
I see an assert in AddDrawCmd, however this is acceptable at this point, and no draw cmd should actually reach your renderer.

If I add the same assert in the renderer
{
+              assert(pcmd->clip_rect.x <= pcmd->clip_rect.z);
+              assert(pcmd->clip_rect.y <= pcmd->clip_rect.w);
                glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd->texture_id);
                glScissor((int)pcmd->clip_rect.x, (int)(height - pcmd->clip_rect.w), (int)(pcmd->clip_rect.z - pcmd->clip_rect.x), (int)(pcmd->clip_rect.w - pcmd->clip_rect.y));
                glDrawArrays(GL_TRIANGLES, vtx_offset, pcmd->vtx_count);
}

It never triggers for me. Does it for you?

**Comment by adamdmoss** [comment]
Oh that's interesting, sorry, I couldn't see how clip rects can make it that far but not make it to the renderer.
I do get an assert if I only assert in the renderer itself, but the repro isn't the same - let me boil up a different repro.

**Comment by ocornut** [comment]
Thanks!
I think at this time it's ok that the rectangle are negative, as the content itself needs to be clipped. But I can totally imagine a case involving childs/scrolling/columns/collapse that won't behave as expected.

**Comment by adamdmoss** [comment]
To reproduce a negative clip-rect getting all the way to the renderer:
* Start this example, collapse its window
* Restart app.
```c++
		if (ImGui::Begin("Foo", NULL, ImVec2(-1,-1), -1, 0))
		{
			ImVec2 cpos;
			cpos.x = ImGui::GetWindowPos().x - 150;
			cpos.y = ImGui::GetWindowPos().y - 150;
			ImVec2 cpos_plus = ImVec2(cpos.x + 2*150, cpos.y + 2*150);
			ImDrawList* draw_list = ImGui::GetWindowDrawList();
			draw_list->AddLine(
					cpos, cpos_plus,
					0xFFFFFFFF, 4);
		}
		ImGui::End();
```
The one-line change you suggest in your first comment fixes this!  But... then #176 is un-fixed. :)

Sorry for the confusion - thanks.

**Comment by adamdmoss** [comment]
Since you say that negative clip rects shouldn't make it to the renderer, I've re-added assertions for this in the opengl example renderers on this branch.

**Comment by ocornut** [comment]
Thanks! Correct the DrawList api isn't software clipped. So I'd need to filter the draw cmd somehow.

**Comment by ocornut** [comment]
Undoing one liner change btw wouldn't be enough of a fix, because the user is not forced to check the return value of ImGui::Begin(). I'll look into it but probably not tonight.
Out of curiosity did it happen for you while using ImDrawList API, or actually doing something else? (aka, is the repro your actual bug situation)
Thanks!

**Comment by adamdmoss** [comment]
I first encountered this about a week ago with the ImDrawList API.  I don't think I've repro'd it outside of drawlists.  That last repro is a minimal approximation of what I'm doing (though I first saw the problem using filled rects rather than lines, if I recall correctly - I think I worked around it by explicitly pushing a full-screen clipping rect, but I'm afraid I don't quite remember now.)
Cheers!

**Comment by adamdmoss** [comment]
Also, this isn't particularly urgent - the GL driver I use doesn't actually explode when this happens, and I'd probably not have ever actually noticed the problem if I wasn't using a debug GL context and a really pedantic break-on-GL-error policy (which has caught some pretty cool bugs outside of imgui).  Still, the GL driver was correct to complain according to glScissor documentation, and I was wondering if this was ever intended imgui behaviour.  That's mainly why I filed the issue. :)

**Comment by ocornut** [comment]
I have fixed the system so a zero-sized clipped rectangle will be passed.
Unfortunately it is still waste of CPU if the user it still submitting to a ImDrawList while the window is collapsed but hopefully that shouldn't be often the case. Closing this for now.
(Down the list we have a few more optimisation we can make to ImDrawList merge call drawing, but unrelated to this)

**Pull request closed without merging**
