### PR TITLE
Added link to Diligent Engine in readme

### PR DESCRIPTION
**Pull request by DiligentGraphics**
Added link to Diligent Engine in readme

### CODE REVIEW

**Comment by ocornut** [comment]
Beware, in git 1 PR = 1 branch
If you add to an existing branch your PR will include old commits.

From https://github.com/ocornut/imgui/issues/2261
> Make sure you create a branch dedicated to the pull request. In Git, 1 PR is associated to 1 branch. If you keep pushing to the same branch after you submitted the PR, your new commits will appear in the PR (we can still cherry-pick individual commits).

**Comment by ocornut** [comment]
I can add it in a subsequent commit don't worry about recreating a branch etc.

**Comment by DiligentGraphics** [comment]
I actually tried to create a new branch, but the merge looks the same.
image

 I guess I should've rebased instead of merging from main repo

**Comment by ocornut** [comment]
I have moved the details out of the README now anyway, there's only a compact list of the languages/frameworks (in which I have added Diligent Engine) and the Wiki has the links/details.
Closing this. Thanks!

**Pull request closed without merging**
