### PR TITLE
Add Thai language support

### PR DESCRIPTION
**Pull request by nProtect**
Add Thai language support via GetGlyphRangesThai()

### CODE REVIEW

**Comment by ocornut** [comment]
Thanks! To apply the PR as-is with your login/commit name please try to follow the coding convention of ImGui (spaces after //, 4-spaces instead of tabs).

**Comment by nProtect** [comment]
OK I have changed tab to spaces. Thanks for recommend me.

**Comment by ocornut** [comment]
I have merged it now and applied fixes. Please pay more attentions when submitting PR in order to make it easier for the project manager to merge changes.
- it was missing spaces after //
- it was still using lots of tabs in imgui_draw.cpp
- there was a typo

Thanks!

**Comment by ocornut** [comment]
#8465 is making the use of glyph range functions unnecessary, so `GetGlyphRangesThai()` will eventually be removed once the work on `dynamic_fonts` is over.

**Pull request closed without merging**
