### PR TITLE
Assert occurs when imgui_freetype is used.

### PR DESCRIPTION
**Pull request by nkari82**
Skip with spacebar (codepoint 32) or only advanceX for glyphs that cannot create image data.

### CODE REVIEW

**Comment by ocornut** [comment]
Hello,

Thanks for the PR but we cannot merge code without understanding a problem.
Please provide a repro that triggers the assert.

**Comment by nkari82** [comment]
Some fonts crash with pack_rect.was_packed set to 0.

Instead, in the case of pack_rect.was_packed 0, we fixed this problem by adding only advanceX of the glyph data without image data.

**Comment by ocornut** [comment]
> Some fonts crash with pack_rect.was_packed set to 0.

Please be specific and provide fonts/size/ranges information.

**Comment by nkari82** [comment]
> > Some fonts crash with pack_rect.was_packed set to 0.
> 
> Please be specific and provide fonts/size/ranges information.

NanumSquareB/18/GlyphRangesKorean

Same information.
https://github.com/ocornut/imgui/pull/5788#issuecomment-1293056267

**Comment by ocornut** [comment]
Hello,
I scratched my head about this for a while, as there was something fishy. 
Stepping through the packing procedure and comparing both variants (stb and freetype packers) I found the fix: eaa2a77
It's a surprisingly innocent-looking fix but has very large effects on packing. I think the sentinel logic of rectpack may have been affected accidentally by this, but I am not sure. Anyhow, which this minor fix it seems like both #5788 and #5829 are correctly fixed.
Thanks for reporting this strange issue!

**Pull request closed without merging**
