### PR TITLE
Clang warning fixes

### PR DESCRIPTION
**Pull request by emoon**

### CODE REVIEW

**Comment by benblo** [comment]
I still get warnings, even with the OFFSETOF () macro ;)

```
g++ -I../../ -I../libs/gl3w `pkg-config --cflags glfw3` -Wall -Wformat -c -o imgui_impl_glfw_gl3.o imgui_impl_glfw_gl3.cpp
imgui_impl_glfw_gl3.cpp: In function ‘bool ImGui_ImplGlfwGL3_CreateDeviceObjects()’:
imgui_impl_glfw_gl3.cpp:260: warning: invalid access to non-static data member ‘ImDrawVert::pos’  of NULL object
imgui_impl_glfw_gl3.cpp:260: warning: (perhaps the ‘offsetof’ macro was used incorrectly)
imgui_impl_glfw_gl3.cpp:261: warning: invalid access to non-static data member ‘ImDrawVert::uv’  of NULL object
imgui_impl_glfw_gl3.cpp:261: warning: (perhaps the ‘offsetof’ macro was used incorrectly)
imgui_impl_glfw_gl3.cpp:262: warning: invalid access to non-static data member ‘ImDrawVert::col’  of NULL object
imgui_impl_glfw_gl3.cpp:262: warning: (perhaps the ‘offsetof’ macro was used incorrectly)
```
On Centos 6 btw.
I suppose those are harmless?

**Comment by ocornut** [comment]
They are harmless, but it'd be interesting to know how your compiler librairies implement the (lowercase) offsetof() macro themselves.

**Comment by benblo** [comment]
No idea :) pretty new to Linux & gcc.
But your macro doesn't make use of it at all right? All I see is this voodoo:
`#define OFFSETOF(TYPE, ELEMENT) ((size_t)&(((TYPE *)0)->ELEMENT))
`

**Comment by Keenuts** [comment]
Hi :)

If the clang, if we use the sanitizer for undefined behaviors, the **IM_OFFSETOF** macro raises some errors at run-time.

A workaround could be to do this:
```cpp
#if defined(__clang__)
# define IM_OFFSETOF(_TYPE, _MEMBER) offsetof(_TYPE, _MEMBER)
#else
# define IM_OFFSETOF(_TYPE,_MEMBER)  ((size_t)&(((_TYPE*)0)->_MEMBER))
#endif
```

Would you be OK with something like that ?

**Comment by ocornut** [comment]
Hello, could you specify what are the warnings and in which version of Clang?
Thank you.

**Comment by Keenuts** [comment]
yes sure, the I had the issue on both clang 6 and clang 8.0.1.

To reproduce:
- clone the repo, branch master
- go to examples/example_glfw_opengl3
- edit Makefile
- build & run

```diff
@@ 12
-#CXX = clang++
+CXX = clang++

@@ 21
-CXXFLAGS = -I../ -I../../
+CXXFLAGS = -I../ -I../../ -fsanitize=undefined -fsanitize-recover=all

@@ 30
-SOURCES += ../libs/gl3w/GL/gl3w.c
-CXXFLAGS += -I../libs/gl3w
+#SOURCES += ../libs/gl3w/GL/gl3w.c
+#CXXFLAGS += -I../libs/gl3w

-# CXXFLAGS = -lGLEW -DIMGUI_IMPL_OPENGL_LOADER_GLEW
+CXXFLAGS += -lGLEW -DIMGUI_IMPL_OPENGL_LOADER_GLEW
```

```
../imgui_impl_opengl3.cpp:216:113: runtime error: member access within null pointer of type 'ImDrawVert'
../imgui_impl_opengl3.cpp:217:113: runtime error: member access within null pointer of type 'ImDrawVert'
../imgui_impl_opengl3.cpp:218:113: runtime error: member access within null pointer of type 'ImDrawVert'
```

**Comment by ocornut** [comment]
Thank you @Keenuts. My next question was to find out in which version of Clang this appeared, but it seems to be a C++11 thing so I am now using `offsetof()` on all C++11 compliant compilers. All my local compiler tests seems to be passing.

**Comment by Keenuts** [comment]
Oh cool, thanks!

**Pull request merged**
