### PR TITLE
ImVector extensions and correction

### PR DESCRIPTION
**Pull request by sergeyn**
1. C++11 move semantics and noexcept for swapping
2. erazing range of zero elements at the end of the array now works and doesn't give an assert
3. There's now std::swap(a,b) for better integration with std library
3. insert now also accepts ranges

### CODE REVIEW

**Comment by ocornut** [comment]
What is your motivation for your changes? You probably shouldn’t be using ImVector in your codebase.

**Comment by sergeyn** [comment]
Hi,
No motivation. Given that it's in public header and it's directly replaceable with std::vector, at least for the subset of functionality I'm using, I just gave it a try. This commit clears out a few things  with your vector.

Regards!

**Comment by ocornut** [comment]
> No motivation

That's not a good enough motivation unfortunately. The change adds 24 lines we would not compile nor test for and have no use of, I don't see a positive point in merging it. ImVector is not meant to be a replacement to std::vector (it doesn't even honor construction, intentionally) so why adding more std-like features we don't use, it's just asking for trouble. 

It's in a public header because some public helpers need it and comments are abuntently explaining that and its restriction / intended use.

I'm not ruling out adding some of those someday (e.g. move semantic, insert range) if there was an actual use case for them later.

**Comment by sergeyn** [comment]
Ok, no problem.

**Pull request closed without merging**
