### PR TITLE
[Win32]: Always update mouse position regardless of focus.

### PR DESCRIPTION
**Pull request by kudaba**
Regarding issue #2445. This is what I've been running with without too much issues. I don't currently have viewports enabled, but that should be running the same logic as before.

### CODE REVIEW

**Comment by kudaba** [comment]
I finally got around to getting viewports up and running, and sure enough the original change wasn't compatible. Viewports still need to use Foreground window since they go transparent and the mouse hover falls through when dragging the window.

**Review by Bit00009 — APPROVED** [review]
Please accept this. this is a feature all standard gui libs has.

**Comment by ocornut** [comment]
> Please accept this. this is a feature all standard gui libs has.

Current PR had too many issues.

I have now pushed three commits to address this consistently in master branch:

SDL 1cdd110
GLFW 044fd0c
Win32 db686ad

- mouse pos is correct when clicking on our host window and dragging outside
- mouse pos is correct when not focused but hovered
- mouse pos is disabled when another window is focused and has capture
- when our window is focused we always report mouse coordinates (that's debatable).

Note that they won't work/merge with docking branch merge (will work on that tomorrow).

**Comment by ocornut** [comment]
This is now fixed for SDL, GLFW and Win32 in both single and multi-viewport mode. Finally closing! :)

**Pull request closed without merging**
