### PR TITLE
Backends: Win32: Cache the result of a windows version check.

### PR DESCRIPTION
**Pull request by learn-more**
This is not expected to change while the application is running :)

### CODE REVIEW

**Comment by ocornut** [comment]
Hello,

This is not called more than once a frame per monitor and I don’t expect those functions to have any sensible performance impact. Have you done any measurement of their cost?

**Comment by ocornut** [comment]
Btw I agree this wouldn’t hurt and best to be merged, but I’m curious if you have any data on perfs of those functions as it would lead us to be more cautious with other calls.

**Comment by learn-more** [comment]
I have not measured this at all, but it was generating logging per call for me.
And since this is not expected to change anyway, there is no gain in re-calculating it every time.

**Comment by ocornut** [comment]
Alright, merged! Thanks!

**Comment by learn-more** [comment]
> Hello, This is not called more than once a frame per monitor and I don’t expect those functions to have any sensible performance impact. Have you done any measurement of their cost?

In the docking branch this is called once per frame per window btw.

**Pull request merged**
