### PR TITLE
Added ability to center per axis by passing -FLT_MAX to which ever axis

### PR DESCRIPTION
**Pull request by inflex**
you want to have centered, ie; ImGui::SetNextWindowPos(ImVec2(-FLT_MAX, 100);

Unsure if you want to have a specific flag to replace -FLT_MAX (ie, windowCenterAxis).

SetNextWindowPos(ImVec2(-FLT_MAX,100)); 
imgui-x-center

SetNextWindowPos(ImVec2(10,-FLT_MAX)); 
imgui-y-center

SetNextWindowPos(ImVec2(-FLT_MAX,-FLT_MAX));
imgui-xy-center

### CODE REVIEW

**Comment by inflex** [comment]
Cannot work out why the formatting is getting mangled. Closing for now.

**Comment by ocornut** [comment]
I may just merge manually the first commit, so perhaps this can be kept open for reference/todo.
Sorry i've been swamped in things to do but intend to merge this :)

**Comment by inflex** [comment]
ja, have seen that you've been very busy, hopefully with important things :+1:    

Hasn't been a problem here as I've just been working off the fork.

I don't understand why the formatting went wrong, my apologies.

**Comment by ocornut** [comment]
I'll reopen this as a reminder to manually merge. No worry!

**Comment by piernov** [comment]
Rebased on v1.50 (and hopefully fixed indentation issue) if it ever helps: piernov/imgui@da070285da2c64766e95757bbb7b883477f46cb9

**Comment by ocornut** [comment]
@inflex, @piernov @srakitnican Sorry I forgot to reply to this, it was actually solved in 1.52 using a different change. I actually forgot to include the change in the release note and this completely slipped off the radar.

The `SetNextWindowPos()` now takes an optional pivot parameter, which you can use for centering or left/right aligning a window.

For example, to do what this PR tried to do with:

`SetNextWindowPos(ImVec2(-FLT_MAX,100));`

We can do:

`SetNextWindowPos(ImVec2(io.DisplaySize.x/2,100), ImVec2(0.5f, 0.0f));`

The X position will match the center (0.5) of the window, while the Y position (100) will match the top (0.0) of the window.

This is generally more flexible and been there since 1.52. Closing this PR.

**Pull request closed without merging**
