### PR TITLE
GLFW: some support for child HWNDs

### PR DESCRIPTION
**Pull request by schwaaa**
Translate window coordinates and handle mouse capture for GLFW windows that are child HWNDs.  At present the only way GLFW windows _can be_ child HWNDs is if the ImGui caller explicitly setparents them.  See https://github.com/ocornut/imgui/issues/4860 for the use case.

### CODE REVIEW

**Comment by ocornut** [comment]
Thanks! I guess this needs to be done on the docking branch, right now it is confused and carrying all docking commits :)

**Comment by schwaaa** [comment]
ah sorry for the noise, I will close this and resubmit.

**Comment by ocornut** [comment]
Please clarify what the second commit does because that sort of stuff is super tricky / subtle with multi-viewports.

i may need to setup a simple repro setup what we can use easily.

**Comment by PathogenDavid** [comment]
> I will close this and resubmit.

@schwaaa FYI for next time, you can click the edit button next to the title of your PR to change the base branch without resubmitting.

**Comment by schwaaa** [comment]
> > I will close this and resubmit.
> 
> @schwaaa FYI for next time, you can click the edit button next to the title of your PR to change the base branch without resubmitting.

Thank you!  Wish I'd known.  I haven't used github for some time and it's much slicker now.

**Pull request closed without merging**
