### PR TITLE
Backends: Win32: dynamically load XInput library

### PR DESCRIPTION
**Pull request by Demonese**
See: https://github.com/ocornut/imgui/issues/3645
Related Pull Request:https://github.com/ocornut/imgui/pull/3248

### CODE REVIEW

**Comment by ocornut** [comment]
Thank you @Demonese. 
This looks good but I'm not going to merge asap as I'm aiming to tag 1.80 soon and don't want to introduce unknown there, but this should be good for 1.81.

I noticed your fixed the batch file, thanks! This was indeed overlooked by b1a18d82 and I've now fixed it with 3346544cf (your PR will conflict because of it, but you can remove the modification to the .bat file and rebase over master + force push if you want, otherwise I'll do it when merging).

I think if you keep `XINPUT_STATE xinput_state;` on the stack as this was the patch would not need to add the extra indentation in `ImGui_ImplWin32_UpdateGamepads()`.

Thanks again!

**Comment by Demonese** [comment]
@ocornut Ok, it's all right now. I will keep this PR up to date because my project is using this improvement.

**Comment by Demonese** [comment]
😋I refer to GLFW's implementation and added searches for XInput1_1.dll and XInput1_2.dll. I also added some cleanup code (line 151-155, maybe you forgot them? @ocornut ):
image

**Comment by ocornut** [comment]
Now merged this, thank you @Demonese!

Your commit 633d103 + various minor amends f139846 (using LoadLibraryA as used elsewhere in the file, moved xinput state back to the stack is simpled and shorter, fixed spacing and minor coding style fixes).

Thanks a lot!

**Pull request closed without merging**
