### PR TITLE
SliderAngle: Added optional `format` argument

### PR DESCRIPTION
**Pull request by podsvirov**
to allow users customize precision and make localization:
slider-angle-format

### CODE REVIEW

**Comment by podsvirov** [comment]
It seems that the `travis-ci` check failed, not because of my changes.

**Comment by ocornut** [comment]
> It seems that the travis-ci check failed, not because of my changes.

Yeah it often fails on package download steps :( don't worry.

Analogous to the default in most functions, could you add a default _in_ `SliderAngle()` ?

```
if (fmt == NULL) 
   fmt = "%.0f deg";
```

(There's also one at compile time in the signature)

**Comment by podsvirov** [comment]
Done.

**Comment by ocornut** [comment]
Merged, thanks!

**Pull request closed without merging**
