### PR TITLE
capture and restore all state

### PR DESCRIPTION
**Pull request by nlguillemot**
caught myself accidentally using leftover state from imgui, decided to fix it thoroughly

### CODE REVIEW

**Comment by ocornut** [comment]
Thanks! This is my nightmare PR. It's totally correct and better, but it is so ugly it makes the example unreadable. I am going to see if I can move all the state to a structure/function see if it makes it less noisy.

**Comment by nlguillemot** [comment]
I see what you mean. Though it's not that much different than the way the GL example does it...

**Comment by ocornut** [comment]
Here's what I got so far

```
// Helper to backup and restore all DX11 state we modify, so this example render function 'ImGui_ImplDX11_RenderDrawLists' can be included in your app and not alter any device state.
// Unfortunately this is very ugly looking and verbose. Close your eyes!
struct BACKUP_DX11_STATE
{
    ID3D11RasterizerState*      RS;                 
    ID3D11BlendState*           BlendState;
    FLOAT                       BlendFactor[4]; 
    UINT                        SampleMask; 
    ID3D11ShaderResourceView*   PSShaderResource;
    ID3D11SamplerState*         PSSampler;          
    ID3D11PixelShader*          PS;        
    ID3D11ClassInstance*        PSInstances[256];   // 256 is max according to PSSetShader documentation
    UINT                        PSInstancesCount;
    ID3D11Buffer*               VSConstantBuffer;              
    ID3D11VertexShader*         VS; 
    ID3D11ClassInstance*        VSInstances[256]; 
    UINT                        VSInstancesCount;
    D3D11_PRIMITIVE_TOPOLOGY    PrimitiveTopology;   
    ID3D11Buffer*               IndexBuffer;
    DXGI_FORMAT                 IndexBufferFormat;
    UINT                        IndexBufferOffset;
    ID3D11Buffer*               VertexBuffer;
    UINT                        VertexBufferStride;
    UINT                        VertexBufferOffset;
    ID3D11InputLayout*          InputLayout;
    UINT                        ScissorRectsCount;
    D3D11_RECT                  ScissorRects[D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE];
    UINT                        ViewportsCount;
    D3D11_VIEWPORT              Viewports[D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE];

    void Backup(ID3D11DeviceContext* ctx)
    {
        ctx->RSGetState(&RS);
        ctx->OMGetBlendState(&BlendState, BlendFactor, &SampleMask);
        ctx->PSGetShaderResources(0, 1, &PSShaderResource);
        ctx->PSGetSamplers(0, 1, &PSSampler);
        PSInstancesCount = 256; 
        ctx->PSGetShader(&PS, PSInstances, &PSInstancesCount);
        ctx->VSGetConstantBuffers(0, 1, &VSConstantBuffer);
        VSInstancesCount = 256; 
        ctx->VSGetShader(&VS, VSInstances, &VSInstancesCount);
        ctx->IAGetPrimitiveTopology(&PrimitiveTopology);
        ctx->IAGetIndexBuffer(&IndexBuffer, &IndexBufferFormat, &IndexBufferOffset);
        ctx->IAGetVertexBuffers(0, 1, &VertexBuffer, &VertexBufferStride, &VertexBufferOffset);
        ctx->IAGetInputLayout(&InputLayout);
        ScissorRectsCount = D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE;
        ctx->RSGetScissorRects(&ScissorRectsCount, ScissorRects);
        ViewportsCount = D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE;
        ctx->RSGetViewports(&ViewportsCount, Viewports);
    }
    
#define DX_RELEASE(_PTR)    if (_PTR) { (_PTR)->Release(); _PTR = NULL; }
    void Restore(ID3D11DeviceContext* ctx)
    {
        ctx->PSSetShaderResources(0, 1, &PSShaderResource); DX_RELEASE(PSShaderResource);
        ctx->RSSetState(RS); DX_RELEASE(RS);
        ctx->OMSetBlendState(BlendState, BlendFactor, SampleMask); DX_RELEASE(BlendState);
        ctx->PSSetSamplers(0, 1, &PSSampler); DX_RELEASE(PSSampler);
        ctx->PSSetShader(PS, PSInstances, PSInstancesCount); DX_RELEASE(PS); for (UINT i = 0; i < PSInstancesCount; i++) DX_RELEASE(PSInstances[i]);
        ctx->VSSetConstantBuffers(0, 1, &VSConstantBuffer); DX_RELEASE(VSConstantBuffer);
        ctx->VSSetShader(VS, VSInstances, VSInstancesCount); DX_RELEASE(VS); for (UINT i = 0; i < VSInstancesCount; i++) DX_RELEASE(VSInstances[i]);
        ctx->IASetPrimitiveTopology(PrimitiveTopology);
        ctx->IASetIndexBuffer(IndexBuffer, IndexBufferFormat, IndexBufferOffset); DX_RELEASE(IndexBuffer); 
        ctx->IASetVertexBuffers(0, 1, &VertexBuffer, &VertexBufferStride, &VertexBufferOffset); DX_RELEASE(VertexBuffer);
        ctx->IASetInputLayout(InputLayout); DX_RELEASE(InputLayout);
        ctx->RSSetScissorRects(ScissorRectsCount, ScissorRects);
        ctx->RSSetViewports(ViewportsCount, Viewports);
    }
#undef DX_RELEASE
};
```

**Comment by ocornut** [comment]
The GL3 one is more terse and packed. 
I would mainly like to avoid increasing the confusion for the first-time user who's not sure to understand how imgui renderer works. So moving the code to a structure-helper here may do the job.

**Comment by nlguillemot** [comment]
definitely looks cleaner packaged like that

**Comment by ocornut** [comment]
Moved them back inside the function like yours, it's more reasonable with better names and alignment:

```
    // Capture all the state that will be modified to restore it afterwards
    ID3D11DeviceContext* ctx = g_pd3dDeviceContext;
    struct BACKUP_DX11_STATE
    {
        UINT                        ScissorRectsCount, ViewportsCount;
        D3D11_RECT                  ScissorRects[D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE];
        D3D11_VIEWPORT              Viewports[D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE];
        ID3D11RasterizerState*      RS;                 
        ID3D11BlendState*           BlendState;
        FLOAT                       BlendFactor[4]; 
        UINT                        SampleMask; 
        ID3D11ShaderResourceView*   PSShaderResource;
        ID3D11SamplerState*         PSSampler;          
        UINT                        PSInstancesCount, VSInstancesCount;
        ID3D11PixelShader*          PS;        
        ID3D11VertexShader*         VS; 
        ID3D11ClassInstance*        PSInstances[256], *VSInstances[256];   // 256 is max according to PSSetShader documentation
        D3D11_PRIMITIVE_TOPOLOGY    PrimitiveTopology;   
        ID3D11Buffer*               IndexBuffer, *VertexBuffer, *VSConstantBuffer;
        UINT                        IndexBufferOffset, VertexBufferStride, VertexBufferOffset;
        DXGI_FORMAT                 IndexBufferFormat;
        ID3D11InputLayout*          InputLayout;
    };
    BACKUP_DX11_STATE old;
    old.ScissorRectsCount = old.ViewportsCount = D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE;
    ctx->RSGetScissorRects(&old.ScissorRectsCount, old.ScissorRects);
    ctx->RSGetViewports(&old.ViewportsCount, old.Viewports);
    ctx->RSGetState(&old.RS);
    ctx->PSGetShaderResources(0, 1, &old.PSShaderResource);
    ctx->OMGetBlendState(&old.BlendState, old.BlendFactor, &old.SampleMask);
    ctx->PSGetSamplers(0, 1, &old.PSSampler);
    old.PSInstancesCount = old.VSInstancesCount = 256;
    ctx->PSGetShader(&old.PS, old.PSInstances, &old.PSInstancesCount);
    ctx->VSGetConstantBuffers(0, 1, &old.VSConstantBuffer);
    ctx->VSGetShader(&old.VS, old.VSInstances, &old.VSInstancesCount);
    ctx->IAGetPrimitiveTopology(&old.PrimitiveTopology);
    ctx->IAGetIndexBuffer(&old.IndexBuffer, &old.IndexBufferFormat, &old.IndexBufferOffset);
    ctx->IAGetVertexBuffers(0, 1, &old.VertexBuffer, &old.VertexBufferStride, &old.VertexBufferOffset);
    ctx->IAGetInputLayout(&old.InputLayout);
```
[...]
```
    // Restore modified state
    ctx->RSSetScissorRects(old.ScissorRectsCount, old.ScissorRects);
    ctx->RSSetViewports(old.ViewportsCount, old.Viewports);
    ctx->RSSetState(old.RS); if (old.RS) old.RS->Release();
    ctx->PSSetShaderResources(0, 1, &old.PSShaderResource); if (old.PSShaderResource) old.PSShaderResource->Release();
    ctx->OMSetBlendState(old.BlendState, old.BlendFactor, old.SampleMask); if (old.BlendState) old.BlendState->Release();
    ctx->PSSetSamplers(0, 1, &old.PSSampler); if (old.PSSampler) old.PSSampler->Release();
    ctx->PSSetShader(old.PS, old.PSInstances, old.PSInstancesCount); if (old.PS) old.PS->Release();
    for (UINT i = 0; i < old.PSInstancesCount; i++) if (old.PSInstances[i]) old.PSInstances[i]->Release();
    ctx->VSSetConstantBuffers(0, 1, &old.VSConstantBuffer); if (old.VSConstantBuffer) old.VSConstantBuffer->Release();
    ctx->VSSetShader(old.VS, old.VSInstances, old.VSInstancesCount); if (old.VS) old.VS->Release();
    for (UINT i = 0; i < old.VSInstancesCount; i++) if (old.VSInstances[i]) old.VSInstances[i]->Release();
    ctx->IASetPrimitiveTopology(old.PrimitiveTopology);
    ctx->IASetIndexBuffer(old.IndexBuffer, old.IndexBufferFormat, old.IndexBufferOffset); if (old.IndexBuffer) old.IndexBuffer->Release();
    ctx->IASetVertexBuffers(0, 1, &old.VertexBuffer, &old.VertexBufferStride, &old.VertexBufferOffset); if (old.VertexBuffer) old.VertexBuffer->Release();
    ctx->IASetInputLayout(old.InputLayout); if (old.InputLayout) old.InputLayout->Release();
```

Down from 63 to 53 line. Some of the structure declaration on same line are a little messy but maybe for the best?

**Comment by ocornut** [comment]
OK this is merged in.
Pinging @JuJuBoSc @nefarius who uses that code to inject into processes, perhaps the additional state backup are fixing some of your use cases? Would you mind having a look.

We need to report the same changes to the DX10 example as well.

**Comment by ocornut** [comment]
Now applied similar changes to DirectX10 example as well.

**Comment by nefarius** [comment]
@ocornut sure thing! Will test these changes ASAP! Thank you for bringing this to our attention!

**Pull request merged**
