### PR TITLE
I have updated the Ubuntu version of Github Actions 

### PR DESCRIPTION
**Pull request by AdamEssemaali**
Version 18.04 to version 20.04, because 18.04 is deprecated :)

### CODE REVIEW

**Comment by ocornut** [comment]
Thank you ! Merged as 7f4b477
Note that CI fails above because your branch is over `string_view` and we have a CI issue with it which I'll also fix now.

**Comment by ocornut** [comment]
I have now rebased `string_view` and fixed its CI warnings.

**Comment by AdamEssemaali** [comment]
I'll make more pull requests for the other branches shortly, they are all with the old ubuntu version

**Comment by AdamEssemaali** [comment]
I make you more pull requests for the other branches, they are all with the old ubuntu version

**Pull request closed without merging**
