### PR TITLE
ImGui::InputTextEx: select text with Shift + LMB clicking too

### PR DESCRIPTION
**Pull request by procedural**
2 lines of code change.

### CODE REVIEW

**Comment by procedural** [comment]
It got so annoying to not have it in my dear imgui-based [gamescript](http://github.com/procedural/gamescript) code editor, I decided to fix it myself and PR the solution 😝

**Comment by ocornut** [comment]
Thank you, this looks like a great improvement. To be fair I'm surprised we didn't get this in earlier (I myself use this from time to time).

I'll need to review this a little more as `InputTextEx()` is notoriously complex, give me some time.

**Comment by procedural** [comment]
@ocornut Sure, no problem! Thank you!

**Comment by ocornut** [comment]
I merged this as 95e609a with a small change of logic. 
I believe it is easier to read this way (compared to 9a1243af). I hope I didn't make a mistake with the change :)

Thank you!

(Also removed a comment I don't understand anymore. If the thing is meaningful/needed we'll find it soon enough)

**Pull request closed without merging**
