### PR TITLE
Fix combo arrow not changing on opening

### PR DESCRIPTION
**Pull request by euyogi**

### CODE REVIEW

**Comment by ocornut** [comment]
This is the same as #6090, see my comment there. What do you think?

**Comment by euyogi** [comment]
hm, indeed doesn't look like standard, roblox studio even does both on the same app. Well looks like the perfect candidate for a flag

dynamicarrowrobloxstudio

**Comment by ocornut** [comment]
I don’t agree that it should be a per-instance flag, this would be promoting inconsistent widget look. If anything it should be a style parameter, but I’m not super inclined to add too many parameters in there for now.

**Comment by euyogi** [comment]
I understand, anyway I think this should be an option somehow, feel free to close

**Comment by ocornut** [comment]
I’ll keep this open until I can decide. Either way it should be in styling reoverhaul later but it may be ok to add before.

**Pull request closed without merging**
