### PR TITLE
Add examples/example_win32_opengl2

### PR DESCRIPTION
**Pull request by podsvirov**
Standalone example application for Win32 + WGL + OpenGL2, using legacy fixed pipeline.

### CODE REVIEW

**Comment by ocornut** [comment]
Hello @podgorskiy, have you looked at #1553 ? (check the patch in the comments at the end).

Your code is simpler so I am interested in it. Presumably partly because it is using old OpenGL, partly some of the writing code (filling `PIXELFORMATDESCRIPTOR` you way you do it is easier).
The issue I had with #1553 is that new viewports would flicker (when using multi-viewports). If your doesn't have this problem or if the problem could be solved for the other PR it'd be good.

What do you use this for?
I've been hesitant to provide this because this is probably a path for lot of people adopting obsolete standards and asking for support. Regular backends are tedious enough :(

**Comment by podsvirov** [comment]
Hello @ocornut, the @podgorskiy account it's not a me, becouse my account is @podsvirov.

I have not tested it for multi-vieports and will try.

> What do you use this for?

I think, that this can be used in education to quick start when learning computer graphics on Windows operation systems. And then learning more affictive and cross-platform solutions.

**Comment by ocornut** [comment]
> becouse my account is @podsvirov.

Sorry for the typo (bad completion! edited the message now)

> I think, that this can be used in education to quick start when learning computer graphics on Windows operation systems. And then learning more affictive and cross-platform solutions.

It seem backward to me to be teaching Win32 + legacy OpenGL when there are so many other ways. I'm asking because I need to protect myself from unnecessary support requests...
(The raw win32 examples are useful/necessary for me mainly because it's not trivial to wire them for multi-viewports.)

**Comment by podsvirov** [comment]
From #1553:

> One possible idea is to merge your code ... in master and specifically NOT attempt to support multi-viewport in this example.

May be for this PR too.

**Comment by ocornut** [comment]
> May be for this PR too.

Actually I realized that the main value for a raw win32 example is to provide the multi-viewport implementation (because it is not obvious / trivial how to do it currently).

**Comment by ocornut** [comment]
Closed/solved, see https://github.com/ocornut/imgui/pull/3218#issuecomment-1514886161

**Pull request closed without merging**
