### PR TITLE
ImFontAtlas::AddFontDefault: Made it possible to override glyph ranges.

### PR DESCRIPTION
**Pull request by tn0502**
Allow overriding glyph ranges when adding default font.

### CODE REVIEW

**Comment by tn0502** [comment]
Thanks for the pointer :D

I was trying to get ⌥ and ⌘ but it seems like "ProggyClean" doesn't include them. Thought it might be useful to someone anyway.

**Comment by ocornut** [comment]
I see. I think it is misleading to add this code if the default font has no extra glyphs available (it doesn't afaik).

I would be interesting - as a separate task - if you we could complete the default ProggyClean with those extra characters. Generally speaking if you are expecting to render fancy characters you would probably load your own font as well.

**Comment by tn0502** [comment]
That's what I ended up doing. I thought this might be useful for people who wants extra control over the glyphs that are loaded, e.g. if you want a smaller subset of the default set to save on resources. If you think this is unnecessary, I wouldn't mind if you closed it ;)

**Comment by ocornut** [comment]
Merged, thank you @tn0502 .

**Pull request merged**
