### PR TITLE
Quadratic Bezier Helpers

### PR DESCRIPTION
**Pull request by aiekick**
3 functions added in imgui_draw.cpp :
add ImQuadBezierCalc
add PathQuadBezierToCasteljau
add PathQuadBezierCurveTo

the Cubic Version was not renamed, just a comment was added to explain the difference

### CODE REVIEW

**Comment by ocornut** [comment]
Merged.

**Comment by ice1000** [comment]
Hi all, I saw entry

> ImDrawList: Added ImDrawList::AddQuadBezierCurve(), ImDrawList::PathQuadBezierCurveTo() quadratic bezier helpers. (#3127, #3664, #3665) [@aiekick]

On the [release notes](https://github.com/ocornut/imgui/releases/tag/v1.80). However these methods seem to be missing. Instead I saw `AddBezierQuadratic` and `PathBezierQuadraticCurveTo`. Are they renamed? If so, I suggest updating the release notes.

**Comment by aiekick** [comment]
In the code of the v1.80, you can see :

```cpp
// cubic version
ImVec2 ImBezierCubicCalc(const ImVec2& p1, const ImVec2& p2, const ImVec2& p3, const ImVec2& p4, float t);
void PathBezierCubicCurveToCasteljau(ImVector<ImVec2>* path, float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4, float tess_tol, int level);
void ImDrawList::PathBezierCubicCurveTo(const ImVec2& p2, const ImVec2& p3, const ImVec2& p4, int num_segments);

// quadratic versions
ImVec2 ImBezierQuadraticCalc(const ImVec2& p1, const ImVec2& p2, const ImVec2& p3, float t);
void PathBezierQuadraticCurveToCasteljau(ImVector<ImVec2>* path, float x1, float y1, float x2, float y2, float x3, float y3, float tess_tol, int level);
void ImDrawList::PathBezierQuadraticCurveTo(const ImVec2& p2, const ImVec2& p3, int num_segments);
```

yes they were renamed if few other ocmmit of Omar.

**Comment by ocornut** [comment]
Hello,
Resurrecting an old topic. @aiekick Can you explain what the *4.0 multiplier is for? It's now in `PathBezierQuadraticCurveToCasteljau()` in latest code?

To better support Mac style DPI scaling I am going to change the `style.CurveTessellationTol` value which is currently in SquaredPixels unit to Pixels unit, so we can easily apply a density factor then square the value before passing to the algorithm. Hence trying to tidying up everything neatly.

**Comment by aiekick** [comment]
Hello,
honestly i don't remember. 
Im pretty sure, its for have a smoother approximation of the curve but maybe most done with eye :) The 4.0r is a weight between the approximation and the exact curve
Maybe a good value for have the best curve shape with the smallest segment count.
:)

**Comment by ocornut** [comment]
It is possible that it makes the max error compare inconsistent between Cubic and Quadratic version, this should be configured as part of the input threshold.
See freshly pushed fdc1152

**Comment by aiekick** [comment]
Yep maybe. 
I surely had a good reason for doing it.
At the time, I was working on ImGuiFontStudio and comparing the quadratic glyph rendering (TTF use quadratics spline for glyphs) I had using the draw API of imgui (who was the reason for this PR) against the actual character rendering on Windows. Without that `*4.0` factor, i guess, the output was not the same as FreeType or stb rasterizers.

**Comment by ocornut** [comment]
You applied a factor to a comparison against a user configurable factor, therefore the user configurable factor can potentially be changed just as well.

**Comment by aiekick** [comment]
yes sure

**Pull request closed without merging**
