### PR TITLE
TreePush with zero arguments was ambiguous. Resolved by making it cal…

### PR DESCRIPTION
**Pull request by JasonWilkins**
…l TreePush(const void*)

### CODE REVIEW

**Comment by ocornut** [comment]
NB: I cannot merge full branch anymore as you pushed 3 unrelated commits to the same branch. It's a very common mistake when using git to not know that PR are associated to a branch.

Will cherry-pick the single commit, no problem.

**Comment by JasonWilkins** [comment]
So that is what was going on.

**Comment by JasonWilkins** [comment]
Even though it is unrelated to the original request, I think you could merge all of this after I fix the problems with 2fce77c, since they are just mismatches between typedefs and missing IMGUI_API tags.

**Comment by ocornut** [comment]
Hello @JasonWilkins, finally looked at this, sorry for the late answer.

TreePush(): Merged 393f9f39856a4f95530127d1dbd9ec7d49444c3c
FindGlyph(): Merged f94f112b35b0a894909d342c0a7c8a4ff2fc1df3

For those commits:
c2e0881213b05276de6acb8ae920f1f7fb5032de
2fce77cb85e0b43336ce96677a52d22fff5bc982
cf0e992c00cd6910a912dc7d10572fecca944929
An equivalent fix had already been applied to Master since you started your branch.

Thanks for your help!

**Comment by JasonWilkins** [comment]
Thanks! Although you explained to me how pull requests work with branches,
I never went back and fixed it.

**Comment by ocornut** [comment]
Followed on this with 513c1ba996f5682141f26cf7b17b04e04171d464

**Pull request closed without merging**
