### PR TITLE
To support drivers with strict core profiles, a buffer is used for th…

### PR DESCRIPTION
**Pull request by trevex**
…e indices as well (fixes ocornut/imgui#277).

### CODE REVIEW

**Comment by ocornut** [comment]
Thanks!

Do you see any reason for not using glBufferData() the same way for the vertex buffer? instead of glMapBufferRange() etc.

**Comment by ocornut** [comment]
Much shorter :) not sure if the old way had any benefit

```cpp
        glBindBuffer(GL_ARRAY_BUFFER, g_VboHandle);
        glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)cmd_list->VtxBuffer.size() * sizeof(ImDrawVert), (GLvoid*)&cmd_list->VtxBuffer.front(), GL_STREAM_DRAW);

        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, g_ElementsHandle);
        glBufferData(GL_ELEMENT_ARRAY_BUFFER, (GLsizeiptr)cmd_list->IdxBuffer.size() * sizeof(ImDrawIdx), (GLvoid*)&cmd_list->IdxBuffer.front(), GL_STREAM_DRAW);
```

**Comment by trevex** [comment]
Didn't spot the possible simplification, but in this case it seems viable. `glMapBufferRange` can be more powerful, if used wisely. A possible future optimisation would be to double buffer the VBO and element buffer. This would allow to use the `GL_MAP_UNSYNCHRONIZED_BIT` and reduce the driver overhead and possible stalling.

**Comment by ocornut** [comment]
We should aim to keep the example as simple as possible really.
If people really want to squeeze extra on the small rendering cost of imgui I'm sure this sort of people will have no issue with doing that.

**Pull request merged**
