### PR TITLE
Changes to ImVec(X)

### PR DESCRIPTION
**Pull request by terryadavis**
Made the ImVec implementations slightly faster/cleaner

### CODE REVIEW

**Comment by ocornut** [comment]
Thank you for the PR!

I'm sorry but at the moment I don't understand the value of those changes
- The `imconfig.h` comment is a guideline for the user, it seems very strange to make it less obvious than the most obvious possible comment?
- `constexpr` is C++11 which is above the minimum specs for imgui for now, especially considering it's only supported from Visual Studio 2015 (might target a subset of C++11 but I imagine we should target Visual Studio ~2010 for portability in the near future).
- The other changes of using initializers + merging the constructions are unlikely to make a difference, but I would be curious if you want to compare disassembly with both full-on debug and optimized builds of major compilers. (Perhaps compare both changes separately, since that's they are two separate changes).

Thank you,
Omar

**Comment by terryadavis** [comment]
@ocornut My bad for the imconfig.h changes realised it wasn't inside of the ImVec structs but why isn't ImGui using (/std:c++latest) wouldn't it be better to be using the latest draft standard.

**Comment by ocornut** [comment]
>  why isn't ImGui using (/std:c++latest) wouldn't it be better to be using the latest draft standard.

No that would be terrible. Many game projects and platforms and teams don't use latest compilers or don't have access to them for variety of reasons. This library also needs to be wrapped and bound to variety of other languages, if not automatically parsed, and fancy C++ features would probably get in the way. Many users of dear imgui would hate it if it even included a C++ header.

If you intend to seriously research the third bullet point I'm happy to leave this open, let me know.

**Comment by terryadavis** [comment]
@ocornut Pretty sure it doesn't matter I'll close this.

**Pull request closed without merging**
