### PR TITLE
Multi viewport dx11 fps fix

### PR DESCRIPTION
**Pull request by lailoken**
As per the issue discussed in https://github.com/ocornut/imgui/issues/7283 , I've managed to get my FPS from under 20 to over 400 (both with vsync disabled).

I'm a novice at DX11 so not sure about the validity of the changes on all versions of windows, but I think these changes are an improvement.

Please review.

### CODE REVIEW

**Comment by lailoken** [comment]
There are 4 edits int the two implementations (main / extra viewports) but they can be grouped into three groups.

With all the edits in place I get 400+FPS with v-sync disabled. (I've seen 800FPS!). With v-sync enabled I get a solid 60FPS.

1) DXGI_PRESENT_DO_NOT_WAIT
I changed this for the extra viewports, but I also changed this in the commented-out main viewport swap.
Removing **only this** flag tanked my FPS to 35FPS in both v-sync and (and non-vsync)

2) DXGI_SWAP_EFFECT_DISCARD -> DXGI_SWAP_EFFECT_FLIP_DISCARD
Removing **only this** edit once again tanked my FPS to around 30FPS with both vsync and non-vsync even with edits in 1.

As for the buffercounts, I saw the two implementations did not match. The problem with leaving it 1 for the extra viewports is that using DXGI_SWAP_EFFECT_FLIP_DISCARD seems to require 2. So that edit is part of 2.

3) As for DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH, this would have been the only change required to bring the two implementations in sync. Also leaving it out for the extra viewports did seem to be (only slightly +-10%) slower. I did not see why the main viewport would allow the user to switch to fullscreen and the other viewports would not, seems inconsistent. (I tried playing around - going fullscreen while I had focus on an extra viewport, switching ImGuiViewportFlags_NoAutoMerge on and off for the extra viewports, but they had no influence here)

So I chalked off 3) as an edit for consistency.

**Comment by lailoken** [comment]
As for the flip swap check, I looked into this and from what I've been reading it is a platform support check and not a compile-time check. It will require at least Windows 10.

So this edit may need to be changed and added as a commented suggestion only.

**Comment by ocornut** [comment]
> As for the flip swap check, I looked into this and from what I've been reading it is a platform support check and not a compile-time check. It will require at least Windows 10.

The symbol doesn't exists in older Windows SDK (e.g. SDK 8.1), it would require a `#ifdef WINVER > 0x0A00`.

Can you clarify also what's your GPU, driver version, and see if you have driver setting enforcing some extra synchronization, and how that may affect those flags?

**Comment by lailoken** [comment]
Ah, of course there may need to be check when it's built. My brain stopped working there. sorry. 
But it also still requires the run-time failover, correct?

PS: Is it `#ifdef WINVER > 0x0A00` or `#ifdef WINVER >= 0x0A00`

**Comment by ocornut** [comment]
> But it also still requires the run-time failover, correct?

Correct.

> PS: Is it #ifdef WINVER > 0x0A00 or #ifdef WINVER >= 0x0A00

Apologies, it is `#ifdef WINVER >= 0x0A00` indeed.

**Comment by lailoken** [comment]
It seems the `DXGI_PRESENT_DO_NOT_WAIT` does not do what I thought it did, and is causing problems.

I apologize, I'll pull this PR until I have it working. 

The DXGI_SWAP_EFFECT_FLIP_DISCARD still looks good (a marginal FPS improvement), but lacks the #defines.

**Pull request closed without merging**
