### PR TITLE
Add Mouse Cursor Hand

### PR DESCRIPTION
**Pull request by aiekick**
Hello,

 this is the PR we discuss today.

i have tested glfw3 and the software rendered version and it look like without software rendering.
i use the official icon size and design if what we have on windows.

i have updated sdl, win32 and glfw3 samples also.

### CODE REVIEW

**Comment by ocornut** [comment]
Did you test the code? The software cursor doesn't work.

**Comment by ocornut** [comment]
(The code that creates the texture compares the characters to 'X' and your ascii drawing uses 'x', it creates an empty texture)

**Comment by aiekick** [comment]
ok not seen that. i created the modification on github and i not seen well the difference. by the way on windows it work :) i will modify it :)

**Comment by aiekick** [comment]
on mingw32 i have that in my editor : 
dllhost_2018-06-29_16-32-18

and the result i have :
devcpp_2018-06-29_16-31-44

but ok its fixed now :)

**Comment by ocornut** [comment]
> on mingw32 i have that in my editor :

Then it mean you are not displaying the software cursor from the code (try to modify the shape and you'll find it it's not used).

**Comment by ocornut** [comment]
I merged with some fixes (see my commit 62b3d7c51e87be48aa08d931453223f9348ccbf7) + squashed your 12 commits into 1. The shape doesn't match Windows 10 cursor shape but it seems to be a pretty common shape (perhaps standard on Windows 7?). Thanks!

**Comment by aiekick** [comment]
ok sorry you are right he was the hardware version. 
i had define io.MouseDrawCursor = true; at a bad place.

:)

**Comment by ocornut** [comment]
I also verified that both GLFW and SDL won't crash when destroying a NULL cursor, which will happen when updating imgui while keeping old backends.

e.g.
https://github.com/glfw/glfw/blob/fdfb5ab466217bb34e38b84333ed286960cc4c75/src/input.c#L749

SDL also has a NULL test.

**Comment by aiekick** [comment]
ok so it work for the three bindings ?

**Pull request closed without merging**
