### PR TITLE
Include custom OpenGL loader header from define.

### PR DESCRIPTION
**Pull request by avostrik**
In case of Windows and custom loader file, no OpenGL API is visible to OpenGL3 implementation.
It is needed to include loader header that provides it.

Can be provided via CMake for example:

`target_compile_definitions(target PRIVATE IMGUI_IMPL_OPENGL_LOADER_CUSTOM="custom_opengl3_loader.h")`

### CODE REVIEW

**Comment by PathogenDavid** [comment]
You don't have to (and generally shouldn't) use the minimal Dear ImGui loader directly, it should only be used by the backend. You can continue to use Glad/GL3W/whatever as per usual for your own code.

**Comment by avostrik** [comment]
> You don't have to (and generally shouldn't) use the minimal Dear ImGui loader directly, it should only be used by the backend. You can continue to use Glad/GL3W/whatever as per usual for your own code.

Unfortunately, two gl3w wrappers in same project do not work together. That is already tried. Nevertheless of my project, if `IMGUI_IMPL_OPENGL_LOADER_CUSTOM` is enabled and ImGui used as usual with OpenGL backend it does not compile as no OpenGL API header provided.

**Comment by ocornut** [comment]
> Unfortunately, two gl3w wrappers in same project do not work together. That is already tried. 

I think you may be on a [XY Problem](https://xyproblem.info) here.

Two OpenGL loaders in same project does/should work. You should focus on solving this.

**Comment by ocornut** [comment]
> Does or should?

It was already discussed in #4445 and it worked then and no changes have been made.

> ImGui with defined custom loader under windows and app provided gl3w does not compile. No GL API visible to ImGui opengl backend.

If you use a custom loader for imgui_impl_opengl3.cpp it needs to expose a GL api, that's the point of a loader.
But you should NOT have to use a custom loader for imgui_impl_opengl3.cpp
The only reason I can currently think of where there is a need to use a custom loader for imgui_impl_opengl3.cpp is unity build (#4646)

> ImGui with its own gl3w loader doesn't link as app provided gl3w defines same functions implementations. (

It should not, we discussed this in #4445 and fixed remaining bugs back then.
Please state exactly what are the conflicts, if there are more we'll fix them.
Note that you did NOT fill the requested issue template and therefore we don't know which version of the Dear ImGui codebase you are using, make sure you are on latest.

The [last known fix](https://github.com/ocornut/imgui/issues/4445#issuecomment-904600610) was merged on Aug 24.

Either way we are discussing a XY Problem. Should solve this instead of using a custom loader for imgui_impl_opengl3.cpp

**Comment by avostrik** [comment]
> We designed our gl3w fork to not have conflicting linking symbols with gl3w.

This is a root cause with conflicting symbols, I used same scripts to generate custom app loader with extended API set.

**Comment by ocornut** [comment]
Ah, that now explains it. You are using a second copy of our loader.
You should NOT use our loader. Use rebular gl3w or anything else.

**Comment by ocornut** [comment]
Closing this. Stance of https://github.com/ocornut/imgui/pull/4649#issuecomment-943248860 stands, you should not use our custom loader for your code we cannot support it (you can use stock GL3W though). Sorry for that.

**Pull request closed without merging**
