### PR TITLE
JANITORIAL: Fix spelling mistakes in comments and text

### PR DESCRIPTION
**Pull request by raziel-**
No code or variables were touched, these are solely typo fixes in either text or comments.

"seeked" should be "sought", but i was told on another project that it is meant as a follow up and explanation to the command of "seek"ing in data, i think it would be best to distinguish it with an added apostrophe (seek'ed).
That way it won' t come up as error anymore and the meaning is still preserved.

I hope i didn't break any rules by simply adding a PR here

### CODE REVIEW

**Comment by ocornut** [comment]
I merged this, thank you!
However, it is possible that the 1 typo in stb_truetype.h and stb_textedit.h may be overridden by a future update as they are updated from another repository.

**Comment by raziel-** [comment]
where does upstream come from for the two files?

**Comment by ocornut** [comment]
https://github.com/nothings/stb/ but good luck getting typo fixes merged in (they are 8 open typos PR).

**Comment by raziel-** [comment]
ugh...132 open PRs...I better skip that then...thanks for the heads up

**Pull request closed without merging**
