### PR TITLE
Cannot create weak reference in file using manual reference counting

### PR DESCRIPTION
**Pull request by whale02**
Solves compile error https://github.com/ocornut/imgui/issues/5122

### CODE REVIEW

**Comment by ocornut** [comment]
Merged tho I honestly don't know what it does/means as I am not an Objective C user. 
I guess if there are side effects we will find out soon !
Thank you!

**Comment by PathogenDavid** [comment]
Also not an Objective C user, but this feels wrong to me considering the variable is named <code><b><i>weak</i></b>Self</code> and @warrenm presumably wrote it that way for a reason.

My vague understanding is this is a difference between Objective C's MMR vs ARC mode. `__weak` only has a meaning in ARC mode, you got that error because your project is using MMR mode. I think without it we might be leaking references to the backend's context and/or vertex/index buffers because the handler passed to `addCompletedHandler` retains `self`? (Although I would think it releases it too, but again, I'm not an Objective C user.)

I think the proper solution would be either to always compile `imgui_impl_metal.mm` in ARC mode, disable the error as [suggested here](https://stackoverflow.com/a/36172977), or maybe use preprocessor to only use `__weak` when ARC is in use.

If the backend is still correct in MMR and ARC and the `__weak` was truly unnecessary, I think at the very least we shouldn't have a separate `weakSelf` anymore since it's not a weak reference.

**Comment by warrenm** [comment]
Yeah, that's not how I would've chosen to "fix" this. At least command buffers are short-lived and holding a strong reference is unlikely to cause lifetime issues. The issue does remain that the variable name is now semantically incorrect.

A better solution would be to enable "Weak References in Manual Retain Release [Mode]" (`-fobjc-weak`) on the hosting project. If that's not available, it would have been preferable to conditionalize the variable declaration on `__has_feature(objc_arc)`, declaring it `__weak` if available and perhaps `__unsafe_unretained` otherwise.

**Comment by ocornut** [comment]
Thank you both for the details. A fix to the PR would be good.
Ideally we want the backend code to compile regardless of projects settings, so conditional compilation would be good.

**Comment by whale02** [comment]
Thank you for your follow up, I updated PR accordingly

**Comment by whale02** [comment]
This works well at my end, using what I believe is the MMR mode. The code base will be mainly C++ so might not be a big deal to stay that way. 

I think git messed me up there, hopefully isn't a big deal if it is let me know how to fix it.

**Comment by warrenm** [comment]
Looks pretty good to me. Thanks for revisiting this with us.

**Comment by ocornut** [comment]
Thank you, merged!

**Pull request merged**
