### PR TITLE
fix compilation on MINGW

### PR DESCRIPTION
**Pull request by fr500**

### CODE REVIEW

**Comment by ocornut** [comment]
Thanks!

Would you mind applying the same patch to the other Makefiles?

**Comment by fr500** [comment]
Well only the GL2 has a makefile I can work with
did so for that one.

The SDL samples don't have them

**Comment by fr500** [comment]
Ok added a SDL makefile too
It works fine

**Comment by ocornut** [comment]
Thanks @fr500, perfect!

**Pull request merged**
